apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nvidia-cuda-validator
  generateName: nvidia-cuda-validator-
  namespace: gpu-operator-resources
spec:
  tolerations:
    - key: nvidia.com/gpu
      operator: Exists
      effect: NoSchedule
  readOnlyRootFilesystem: true
  restartPolicy: OnFailure
  serviceAccount: nvidia-operator-validator
  runtimeClassName: nvidia
  initContainers:
  - name: cuda-validation
    image: "FILLED_BY_VALIDATOR"
    imagePullPolicy: IfNotPresent
    command: ['sh', '-c']
    args: ["vectorAdd"]
    securityContext:
      allowPrivilegeEscalation: false
  containers:
    - name: nvidia-cuda-validator
      image: "FILLED_BY_VALIDATOR"
      imagePullPolicy: IfNotPresent
      # override command and args as validation is already done by initContainer
      command: ['sh', '-c']
      args: ["echo cuda workload validation is successful"]
      securityContext:
        allowPrivilegeEscalation: false