apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nvidia-device-plugin-validator
  generateName: nvidia-device-plugin-validator-
  namespace: "FILLED_BY_VALIDATOR"
spec:
  tolerations:
    - key: nvidia.com/gpu
      operator: Exists
      effect: NoSchedule
  readOnlyRootFilesystem: true
  restartPolicy: OnFailure
  serviceAccount: nvidia-operator-validator
  initContainers:
    - name: plugin-validation
      image: "FILLED_BY_VALIDATOR"
      imagePullPolicy: Always
      command: ["sh", "-c"]
      args: ["vectorAdd"]
      env:
        - name: NVIDIA_VISIBLE_DEVICES
          value: "all"
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: compute,utility
      securityContext:
        allowPrivilegeEscalation: false
  containers:
    - name: nvidia-device-plugin-validator
      image: "FILLED_BY_VALIDATOR"
      imagePullPolicy: Always
      # override command and args as validation is already done by initContainer
      command: ["sh", "-c"]
      args: ["echo device-plugin workload validation is successful"]
      securityContext:
        allowPrivilegeEscalation: false
